### PR TITLE
【PR】firebase set up and output the data of cloud firestore.

### PR DESCRIPTION
**Pull request by Tanesan**
(((((((デザインが崩れたかもだから直して欲しい))))))

### CODE REVIEW

**Comment by Tanesan** [comment]
To begin with, I don't have an IOS setup, so **it's not surprising that it doesn't work.** Therefore, I have added IOS settings.

**Comment by mox692** [comment]
@Tanesan 
Thanks,
I'll check [it](https://github.com/JobInterviewPractice/job_interview_practice/pull/12/commits/3d0e84eb31057fa62cca26bb9ffbe599a6282004)

**Comment by mox692** [comment]
@Tanesan 
I still got the same error....。
can you run the app in IOS mode on your machine ??

If not, i think we should set again according to [this](https://codelabs.developers.google.com/codelabs/flutter-firebase#0).  


* err log
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                            8.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    error: /Users/kimuramotoyuki/flutter_project/job_interview_practice/ios/Pods/gRPC-C++/etc/roots.pem: No such file or directory (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
    error: the following command failed with exit code 1 but produced no further output
    CpResource /Users/kimuramotoyuki/flutter_project/job_interview_practice/ios/Pods/gRPC-C++/etc/roots.pem /Users/kimuramotoyuki/flutter_project/job_interview_practice/build/ios/Debug-iphonesimulator/gRPC-C++/gRPCCertificates-Cpp.bundle/roots.pem
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'nanopb' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'BoringSSL-GRPC' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'GoogleDataTransport' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'gRPC-C++' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'FirebaseCore' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'gRPC-Core' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'cloud_firestore' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'Firebase' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'FirebaseCoreDiagnostics' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'GoogleUtilities' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'FirebaseFirestore' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'abseil' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'leveldb-library' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'Flutter' from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'firebase_core' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

```

**Comment by Tanesan** [comment]
@mox692 
Of course, I can do it.
I know that error. I have experienced it. Just in case, I talked to my hackathon flutter team about this bug, they said that you have to go to the IOS directory and pod init.
Thank you.

**Comment by mox692** [comment]
@Tanesan 
After running `pod install`,  I can't still run :(
Can you send All project file (**including gitignoredfile**) by .zip or something ? slackかどっかに🙏

**Comment by lewandowskit93** [comment]
@mox692 
Hi, have you tried cloning a fresh repo?

@Tanesan
I would add back the gitignore files or else you will possibly end up with a huge problems on the repo

**Comment by Tanesan** [comment]
I leave it as it is.
@mox692 Can you move it now? I send to the slack all file.

**Comment by mox692** [comment]
@lewandowskit93 
Hi :)
I haven't tried yet.
I'll try it. If that doesn't work, I'll rebase this branch.

**Comment by mox692** [comment]
I'll mergeI was able to do most of what I wanted to do with this branch. I thinnk I'll merge this branch soon :)

**Pull request merged**
